### ISSUE TITLE
Error in no_dry_run() showing up in tests

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#773]
After enabling messages for the client.py unit tests, I noticed these errors:

These appear to be showing up on account of the unit tests setting `dry_run=true`.

```
INFO:haas.rest:In request context ec0e31f1-1ee2-4478-a324-63bb26f822a3: API call: node_power_off(node=u'node-07')
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not enough arguments for format string
```

**Comment by naved001** [comment]
this seems similar to what we fixed here https://github.com/CCI-MOC/hil/pull/766

**Comment by zenhack** [comment]
Yeah, that's definitely the same problem.
